//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance
    {
        public int AttendanceId { get; set; }
        public int UserId { get; set; }
        public System.DateTime PunchIn { get; set; }
        public string PunchInMessage { get; set; }
        public Nullable<System.DateTime> PunchOut { get; set; }
        public string PunchOutMessage { get; set; }
        public Nullable<System.TimeSpan> Duration { get; set; }
    
        public virtual User User { get; set; }
    }
}
