//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveDuration
    {
        public LeaveDuration()
        {
            this.LeaveRequests = new HashSet<LeaveRequest>();
            this.Holidays = new HashSet<Holiday>();
        }
    
        public int DurationId { get; set; }
        public string DurationType { get; set; }
        public double NoOfDay { get; set; }
    
        public virtual ICollection<LeaveRequest> LeaveRequests { get; set; }
        public virtual ICollection<Holiday> Holidays { get; set; }
    }
}
