//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveType
    {
        public LeaveType()
        {
            this.LeaveRequests = new HashSet<LeaveRequest>();
        }
    
        public int TypeId { get; set; }
        public string TypeName { get; set; }
    
        public virtual ICollection<LeaveRequest> LeaveRequests { get; set; }
    }
}
