//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Attendances = new HashSet<Attendance>();
            this.LeaveRequests = new HashSet<LeaveRequest>();
        }
    
        public int UserId { get; set; }
        public string Guid { get; set; }
        public string Name { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public string PersonalEmail { get; set; }
        public bool Status { get; set; }
        public int ManagerId { get; set; }
        public Nullable<int> DesignationId { get; set; }
        public string ContactNo { get; set; }
        public string Address { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public string Image { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<System.DateTime> DOJ { get; set; }
        public Nullable<System.DateTime> DOR { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual ICollection<Attendance> Attendances { get; set; }
        public virtual Designation Designation { get; set; }
        public virtual ICollection<LeaveRequest> LeaveRequests { get; set; }
    }
}
